FROM ubuntu:20.04 as builder
RUN apt-get -y update
ENV TZ=Europe/Stockholm
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get -y install curl git libssl-dev libudev-dev make pkg-config zlib1g-dev llvm clang

RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
RUN rustup component add rustfmt && rustup update

COPY . /solana
WORKDIR /solana
RUN cargo  doc --release


FROM nginx as dest

COPY --from=builder /solana/target/doc/ /usr/share/nginx/html
COPY docker/nginx_doc.conf /etc/nginx/conf.d/default.conf
